USE [master]
GO

/****** Object:  Database [Estabelecimento]    Script Date: 07/10/2018 14:52:20 ******/
CREATE DATABASE [Estabelecimento]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Estabelecimento', FILENAME = N'C:\Program Files\MSSQL14.MSSQLSERVER\MSSQL\DATA\Estabelecimento.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Estabelecimento_log', FILENAME = N'C:\Program Files\MSSQL14.MSSQLSERVER\MSSQL\DATA\Estabelecimento_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Estabelecimento] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Estabelecimento].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Estabelecimento] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Estabelecimento] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Estabelecimento] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Estabelecimento] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Estabelecimento] SET ARITHABORT OFF 
GO

ALTER DATABASE [Estabelecimento] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Estabelecimento] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Estabelecimento] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Estabelecimento] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Estabelecimento] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Estabelecimento] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Estabelecimento] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Estabelecimento] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Estabelecimento] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Estabelecimento] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Estabelecimento] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Estabelecimento] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Estabelecimento] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Estabelecimento] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Estabelecimento] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Estabelecimento] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Estabelecimento] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Estabelecimento] SET RECOVERY FULL 
GO

ALTER DATABASE [Estabelecimento] SET  MULTI_USER 
GO

ALTER DATABASE [Estabelecimento] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Estabelecimento] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Estabelecimento] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Estabelecimento] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Estabelecimento] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Estabelecimento] SET QUERY_STORE = OFF
GO

USE [Estabelecimento]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Estabelecimento] SET  READ_WRITE 
GO

